In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=np.zeros((5,3))
c=np.random.random((5,3))
d=np.arange(0,50,2)
e=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newe=e.reshape((3,5))
flat=a.flatten()
print("\n array:\n",a)
print("\n array with all zeros:\n",b)
print("\n array with random values:\n",c)
print("\n range value:\n",d)
print("\n original array:\n",e)
print("\n reshaped array[3,5]:\n",newe)
print("flattened array:\n",flat)
print("\n no.of dimensions:",a.ndim)
print("\n array element type:",a.dtype)


 array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 array with random values:
 [[0.84148189 0.34329945 0.89050785]
 [0.78285064 0.36786055 0.26544981]
 [0.14416281 0.43121881 0.94369912]
 [0.27400076 0.82049794 0.46759633]
 [0.63129349 0.04602628 0.10942767]]

 range value:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]

 original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 reshaped array[3,5]:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 no.of dimensions: 2

 array element type: int32


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n shape of array:",a.shape)


 shape of array: (5, 3)


In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
newtype=arr.astype("f")
print("\n convert array element:\n",newtype)
print("converted array:",newtype.dtype)


 convert array element:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
converted array: float32


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
size=len(arr)
print("\n size of array:\n",arr.size)


 size of array:
 9
